name: EKS Cluster Management

on:
  workflow_dispatch: # This workflow can be triggered manually from GitHub UI.

jobs:
  create-eks-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step to install eksctl
    - name: Install eksctl
      run: |
        # Download the latest release of eksctl
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.106.0/eksctl_Linux_amd64.tar.gz" -o eksctl_Linux_amd64.tar.gz
        # Extract the binary and move it to /usr/local/bin
        tar -xzf eksctl_Linux_amd64.tar.gz
        sudo mv eksctl /usr/local/bin

    # Verify eksctl installation
    - name: Verify eksctl version
      run: |
        eksctl version
